id: P010605
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19228
  title: ཁམས་གཙང་འབྲུག་རྒྱལ་གྱི་སྨན་ཡིག།
  author: ''
  volumes:
    50c09cc0501d461f9e3fd66ed098cb2d:
      image_group_id: I8LS19230
      title: ''
      volume_number: 1
      total_pages: 858
      base_file: v001.txt
