id: I54CC5058
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:45:34+00:00'
last_modified: '2022-06-08T16:11:31.129786+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19228
  title: ཁམས་གཙང་འབྲུག་རྒྱལ་གྱི་སྨན་ཡིག།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    74E3:
      image_group_id: I8LS19230
      title: ''
      total_pages: 858
      order: 1
      base_file: 74E3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
